# Generated by Django 4.2.1 on 2023-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_varificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='varificationcode',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
    ]
